
ALTER INDEX SYS_C008813 RENAME TO FIDE_GENEROS_TB_Genero_ID_IDX;
ALTER INDEX SYS_C008815 RENAME TO FIDE_PROVINCIAS_TB_Provincia_ID_IDX;
ALTER INDEX SYS_C008816 RENAME TO FIDE_PROVINCIAS_TB_Nombre_IDX;

ALTER INDEX SYS_C008818 RENAME TO FIDE_CANTONES_TB_Canton_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_CANTONES_TB_Provincia_ID_IDX;
ALTER INDEX SYS_C008819 RENAME TO FIDE_CANTONES_TB_Nombre_IDX;

ALTER INDEX SYS_C008821 RENAME TO FIDE_DISTRITOS_TB_Distrito_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_DISTRITOS_TB_Canton_ID_IDX;
ALTER INDEX SYS_C008822 RENAME TO FIDE_DISTRITOS_TB_Nombre_IDX;

ALTER INDEX SYS_C008823 RENAME TO FIDE_DIRECCIONES_TB_Direccion_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_DIRECCIONES_TB_Provincia_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_DIRECCIONES_TB_Canton_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_DIRECCIONES_TB_Distrito_ID_IDX;

ALTER INDEX SYS_C008831 RENAME TO FIDE_VOTANTES_TB_Votante_ID_IDX;
ALTER INDEX SYS_C008832 RENAME TO FIDE_VOTANTES_TB_Email_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_VOTANTES_TB_Genero_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_VOTANTES_TB_Direccion_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_VOTANTES_TB_Estado_ID_IDX;

ALTER INDEX SYS_C008839 RENAME TO FIDE_ELECCIONES_TB_Eleccion_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_ELECCIONES_TB_Estado_ID_IDX;

ALTER INDEX SYS_C008843 RENAME TO FIDE_PARTIDOS_TB_Partido_ID_IDX;
ALTER INDEX SYS_C008844 RENAME TO FIDE_PARTIDOS_TB_Nombre_IDX;
ALTER INDEX SYS_C008845 RENAME TO FIDE_PARTIDOS_TB_Siglas_Partido_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_PARTIDOS_TB_Estado_ID_IDX;
--Índices para FIDE_CANDIDATOS_TB
ALTER INDEX SYS_C008849 RENAME TO FIDE_CANDIDATOS_TB_Candidato_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_CANDIDATOS_TB_Partido_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_CANDIDATOS_TB_Eleccion_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_CANDIDATOS_TB_Estado_ID_IDX;
--Índices para FIDE_ROLES_TB
ALTER INDEX SYS_C008854 RENAME TO FIDE_ROLES_TB_Rol_ID_IDX;
ALTER INDEX SYS_C008855 RENAME TO FIDE_ROLES_TB_Nombre_Rol_IDX;
--Índices para FIDE_USUARIOS_TB
ALTER INDEX SYS_C008859 RENAME TO FIDE_USUARIOS_TB_Usuario_ID_IDX;
ALTER INDEX SYS_C008860 RENAME TO FIDE_USUARIOS_TB_User_name_IDX;
ALTER INDEX SYS_C008861 RENAME TO FIDE_USUARIOS_TB_Email_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_USUARIOS_TB_Rol_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_USUARIOS_TB_Estado_ID_IDX;
--Índices para FIDE_AUDITORES_TB
ALTER INDEX SYS_C008867 RENAME TO FIDE_AUDITORES_TB_Auditor_ID_IDX;
ALTER INDEX SYS_C008868 RENAME TO FIDE_AUDITORES_TB_Email_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_AUDITORES_TB_Estado_ID_IDX;
--Índices para FIDE_AUDITORIAS_TB
ALTER INDEX SYS_C008870 RENAME TO FIDE_AUDITORIAS_TB_Auditoria_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_AUDITORIAS_TB_Eleccion_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_AUDITORIAS_TB_Auditor_ID_IDX;
--Índices para FIDE_SEDES_TB
ALTER INDEX SYS_C008874 RENAME TO FIDE_SEDES_TB_Sede_ID_IDX;
ALTER INDEX SYS_C008875 RENAME TO FIDE_SEDES_TB_Nombre_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_SEDES_TB_Direccion_ID_IDX;
--Índices para FIDE_VOTOS_TB
ALTER INDEX SYS_C008878 RENAME TO FIDE_VOTOS_TB_Voto_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_VOTOS_TB_Votante_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_VOTOS_TB_Eleccion_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_VOTOS_TB_Candidato_ID_IDX;
--Índices para FIDE_MESAS_VOTO_TB
ALTER INDEX SYS_C008882 RENAME TO FIDE_MESAS_VOTO_TB_Mesa_Voto_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_MESAS_VOTO_TB_Eleccion_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_MESAS_VOTO_TB_Votante_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_MESAS_VOTO_TB_Estado_ID_IDX;
--Índices para FIDE_CREDENCIALES_TB
ALTER INDEX SYS_C008888 RENAME TO FIDE_CREDENCIALES_TB_Credencial_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_CREDENCIALES_TB_Votante_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_CREDENCIALES_TB_Eleccion_ID_IDX;
ALTER INDEX SYS_C008889 RENAME TO FIDE_CREDENCIALES_TB_Codigo_IDX;
--Índices para FIDE_REPORTES_TB
ALTER INDEX SYS_C008893 RENAME TO FIDE_REPORTES_TB_Reporte_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_REPORTES_TB_Eleccion_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_REPORTES_TB_Votante_ID_IDX;
--Índices para FIDE_BOLETAS_TB
ALTER INDEX SYS_C008897 RENAME TO FIDE_BOLETAS_TB_Boleta_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_BOLETAS_TB_Eleccion_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_BOLETAS_TB_Votante_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_BOLETAS_TB_Candidato_ID_IDX;
--Índices para FIDE_CLAVES_SEGURIDAD_TB
ALTER INDEX SYS_C008903 RENAME TO FIDE_CLAVES_SEGURIDAD_TB_Clave_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_CLAVES_SEGURIDAD_TB_Votante_ID_IDX;
--Índices para FIDE_LOGSEGURIDAD_TB
ALTER INDEX SYS_C008907 RENAME TO FIDE_LOGSEGURIDAD_TB_Log_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_LOGSEGURIDAD_TB_Votante_ID_IDX;
--Índices para FIDE_NOTIFICACIONES_TB
ALTER INDEX SYS_C008911 RENAME TO FIDE_NOTIFICACIONES_TB_Notificacion_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_NOTIFICACIONES_TB_Votante_ID_IDX;
--Índices para FIDE_SESIONES_TB
ALTER INDEX SYS_C008914 RENAME TO FIDE_SESIONES_TB_Sesion_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_SESIONES_TB_Usuario_ID_IDX;
--Índices para FIDE_HISTORIALVOTOS_TB
ALTER INDEX SYS_C008918 RENAME TO FIDE_HISTORIALVOTOS_TB_Historial_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_HISTORIALVOTOS_TB_Votante_ID_IDX;
--Índices para FIDE_VOTOS_HISTORIAL_TB
ALTER INDEX SYS_C008919 RENAME TO FIDE_VOTOS_HISTORIAL_TB_Votos_Historial_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_VOTOS_HISTORIAL_TB_Voto_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_VOTOS_HISTORIAL_TB_Historial_ID_IDX;
--Índices para FIDE_RESULTADOS_TB
ALTER INDEX SYS_C008922 RENAME TO FIDE_RESULTADOS_TB_Resultado_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_RESULTADOS_TB_Eleccion_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_RESULTADOS_TB_Candidato_ID_IDX;
--ALTER INDEX nombre_actual RENAME TO FIDE_RESULTADOS_TB_Estado_ID_IDX;