---PRIMERA TABLA
CREATE TABLE FIDE_ESTADOS_TB(
    Estado_ID NUMBER PRIMARY KEY,
    Descripcion VARCHAR2(100),
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100)
);

CREATE INDEX FIDE_ESTADOS_TB_DESCRIPCION_IDX 
ON FIDE_ESTADOS_TB (Descripcion);

CREATE INDEX FIDE_ESTADOS_TB_CREADO_POR_IDX 
ON FIDE_ESTADOS_TB (creado_por);

CREATE INDEX FIDE_ESTADOS_TB_MODIFICADO_POR_IDX 
ON FIDE_ESTADOS_TB (modificado_por);

CREATE INDEX FIDE_ESTADOS_TB_FECHA_CREACION_IDX 
ON FIDE_ESTADOS_TB (fecha_creacion);

CREATE INDEX FIDE_ESTADOS_TB_FECHA_MODIFICACION_IDX 
ON FIDE_ESTADOS_TB (fecha_modificacion);

CREATE INDEX FIDE_ESTADOS_TB_ACCION_IDX 
ON FIDE_ESTADOS_TB (accion);
/
ALTER INDEX SYS_C008573 ---Este SYS se cambia por el que sale automaticamente cuando se crea la primary key
RENAME TO FIDE_ESTADOS_TB_ESTADO_ID_PK_IDX;
/
---SEGUNDA TABLA
CREATE TABLE FIDE_GENEROS_TB(
    Genero_ID NUMBER PRIMARY KEY,
    Nombre VARCHAR2(20),
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100)
);
/
CREATE INDEX FIDE_GENEROS_TB_NOMBRE_IDX 
ON FIDE_GENEROS_TB (Nombre);


CREATE INDEX FIDE_GENEROS_TB_CREADO_POR_IDX 
ON FIDE_GENEROS_TB (creado_por);


CREATE INDEX FIDE_GENEROS_TB_MODIFICADO_POR_IDX 
ON FIDE_GENEROS_TB (modificado_por);


CREATE INDEX FIDE_GENEROS_TB_FECHA_CREACION_IDX 
ON FIDE_GENEROS_TB (fecha_creacion);


CREATE INDEX FIDE_GENEROS_TB_FECHA_MODIFICACION_IDX 
ON FIDE_GENEROS_TB (fecha_modificacion);


CREATE INDEX FIDE_GENEROS_TB_ACCION_IDX 
ON FIDE_GENEROS_TB (accion);
/
ALTER INDEX SYS_C008575 ---ESTE SE CAMBIA POR EL PRIMARY KEY
RENAME TO FIDE_GENEROS_TB_GENERO_ID_PK_IDX;
/
---TERCERA TABLA
CREATE TABLE FIDE_PROVINCIAS_TB(
    Provincia_ID NUMBER PRIMARY KEY,
    Nombre VARCHAR2(20) UNIQUE NOT NULL,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100)
);
CREATE INDEX FIDE_PROVINCIAS_TB_CREADO_POR_IDX 
ON FIDE_PROVINCIAS_TB (creado_por);


CREATE INDEX FIDE_PROVINCIAS_TB_MODIFICADO_POR_IDX 
ON FIDE_PROVINCIAS_TB (modificado_por);


CREATE INDEX FIDE_PROVINCIAS_TB_FECHA_CREACION_IDX 
ON FIDE_PROVINCIAS_TB (fecha_creacion);


CREATE INDEX FIDE_PROVINCIAS_TB_FECHA_MODIFICACION_IDX 
ON FIDE_PROVINCIAS_TB (fecha_modificacion);


CREATE INDEX FIDE_PROVINCIAS_TB_ACCION_IDX 
ON FIDE_PROVINCIAS_TB (accion);
/
ALTER INDEX SYS_C008577 ---ESTE SE CAMBIA POR EL PRIMARY KEY
RENAME TO FIDE_PROVINCIAS_TB_PROVINCIA_ID_PK_IDX;
/
ALTER INDEX SYS_C008578 ---ESTE SE CAMBIA POR EL UNIQUE
RENAME TO FIDE_PROVINCIAS_TB_NOMBRE_UQ_IDX;
/
---CUARTA TABLA
CREATE TABLE FIDE_CANTONES_TB(
    Canton_ID NUMBER PRIMARY KEY,
    Nombre VARCHAR2(20) UNIQUE NOT NULL,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100)
);
/
CREATE INDEX FIDE_CANTONES_TB_CREADO_POR_IDX 
ON FIDE_CANTONES_TB (creado_por);


CREATE INDEX FIDE_CANTONES_TB_MODIFICADO_POR_IDX 
ON FIDE_CANTONES_TB (modificado_por);


CREATE INDEX FIDE_CANTONES_TB_FECHA_CREACION_IDX 
ON FIDE_CANTONES_TB (fecha_creacion);


CREATE INDEX FIDE_CANTONES_TB_FECHA_MODIFICACION_IDX 
ON FIDE_CANTONES_TB (fecha_modificacion);


CREATE INDEX FIDE_CANTONES_TB_ACCION_IDX 
ON FIDE_CANTONES_TB (accion);
/
ALTER INDEX SYS_C008581 ---ESTE SE CAMBIA POR EL UNIQUE
RENAME TO FIDE_CANTONES_TB_NOMBRE_UQ_IDX;
/
ALTER INDEX SYS_C008580 ---ESTE SE CAMBIA POR SER PRIMARY KEY
RENAME TO FIDE_CANTONES_TB_CANTON_ID_PK_IDX;
/
---QUINTA TABLA
CREATE TABLE FIDE_DISTRITOS_TB(
    Distrito_ID NUMBER PRIMARY KEY,
    Nombre VARCHAR2(20) UNIQUE NOT NULL,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100)
);
/
CREATE INDEX FIDE_DISTRITOS_TB_CREADO_POR_IDX 
ON FIDE_DISTRITOS_TB (creado_por);


CREATE INDEX FIDE_DISTRITOS_TB_MODIFICADO_POR_IDX 
ON FIDE_DISTRITOS_TB (modificado_por);


CREATE INDEX FIDE_DISTRITOS_TB_FECHA_CREACION_IDX 
ON FIDE_DISTRITOS_TB (fecha_creacion);


CREATE INDEX FIDE_DISTRITOS_TB_FECHA_MODIFICACION_IDX 
ON FIDE_DISTRITOS_TB (fecha_modificacion);

CREATE INDEX FIDE_DISTRITOS_TB_ACCION_IDX 
ON FIDE_DISTRITOS_TB (accion);

-----------------------------------------------------
ALTER INDEX SYS_C008583 
RENAME TO FIDE_DISTRITOS_TB_DISTRITO_ID_PK_IDX;

ALTER INDEX SYS_C008584 
RENAME TO FIDE_DISTRITOS_TB_NOMBRE_UQ_IDX;
/
---SEXTA TABLA
CREATE TABLE FIDE_DIRECCIONES_TB(
    Direccion_ID NUMBER PRIMARY KEY,
    Provincia_ID NUMBER,
    Canton_ID NUMBER,
    Distrito_ID NUMBER,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Provincia_ID) REFERENCES FIDE_PROVINCIAS_TB(Provincia_ID),
    FOREIGN KEY (Canton_ID) REFERENCES FIDE_CANTONES_TB(Canton_ID),
    FOREIGN KEY (Distrito_ID) REFERENCES FIDE_DISTRITOS_TB(Distrito_ID)
);
/
CREATE INDEX FIDE_DIRECCIONES_TB_PROVINCIA_ID_IDX 
ON FIDE_DIRECCIONES_TB (Provincia_ID);

CREATE INDEX FIDE_DIRECCIONES_TB_CANTON_ID_IDX 
ON FIDE_DIRECCIONES_TB (Canton_ID);

CREATE INDEX FIDE_DIRECCIONES_TB_DISTRITO_ID_IDX 
ON FIDE_DIRECCIONES_TB (Distrito_ID);

CREATE INDEX FIDE_DIRECCIONES_TB_CREADO_POR_IDX 
ON FIDE_DIRECCIONES_TB (creado_por);

CREATE INDEX FIDE_DIRECCIONES_TB_MODIFICADO_POR_IDX 
ON FIDE_DIRECCIONES_TB (modificado_por);

CREATE INDEX FIDE_DIRECCIONES_TB_FECHA_CREACION_IDX 
ON FIDE_DIRECCIONES_TB (fecha_creacion);

CREATE INDEX FIDE_DIRECCIONES_TB_FECHA_MODIFICACION_IDX 
ON FIDE_DIRECCIONES_TB (fecha_modificacion);

CREATE INDEX FIDE_DIRECCIONES_TB_ACCION_IDX 
ON FIDE_DIRECCIONES_TB (accion);
/
----------------------------------------------------------------
ALTER INDEX SYS_C008585 
RENAME TO FIDE_DIRECCIONES_TB_DIRECCION_ID_PK_IDX;
/
---SEPTIMA TABLA
CREATE TABLE FIDE_VOTANTES_TB(
    Votante_ID NUMBER PRIMARY KEY,
    Nombre VARCHAR2(50) NOT NULL,
    Apellido VARCHAR2(50) NOT NULL,
    Fecha_Nacimiento DATE NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Telefono VARCHAR2(8),
    Genero_ID NUMBER,
    Direccion_ID NUMBER,
    Estado_ID NUMBER,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Genero_ID) REFERENCES FIDE_GENEROS_TB(Genero_ID),
    FOREIGN KEY (Direccion_ID) REFERENCES FIDE_DIRECCIONES_TB(Direccion_ID),
    FOREIGN KEY (Estado_ID) REFERENCES FIDE_ESTADOS_TB(Estado_ID)
);
/

CREATE INDEX FIDE_VOTANTES_TB_NOMBRE_IDX 
ON FIDE_VOTANTES_TB (Nombre);

CREATE INDEX FIDE_VOTANTES_TB_APELLIDO_IDX 
ON FIDE_VOTANTES_TB (Apellido);

CREATE INDEX FIDE_VOTANTES_TB_FECHA_NACIMIENTO_IDX 
ON FIDE_VOTANTES_TB (Fecha_Nacimiento);

CREATE INDEX FIDE_VOTANTES_TB_TELEFONO_IDX 
ON FIDE_VOTANTES_TB (Telefono);

CREATE INDEX FIDE_VOTANTES_TB_CREADO_POR_IDX 
ON FIDE_VOTANTES_TB (creado_por);

CREATE INDEX FIDE_VOTANTES_TB_MODIFICADO_POR_IDX 
ON FIDE_VOTANTES_TB (modificado_por);

CREATE INDEX FIDE_VOTANTES_TB_FECHA_CREACION_IDX 
ON FIDE_VOTANTES_TB (fecha_creacion);

CREATE INDEX FIDE_VOTANTES_TB_FECHA_MODIFICACION_IDX 
ON FIDE_VOTANTES_TB (fecha_modificacion);

CREATE INDEX FIDE_VOTANTES_TB_ACCION_IDX 
ON FIDE_VOTANTES_TB (accion);

CREATE INDEX FIDE_VOTANTES_TB_GENERO_ID_FK_IDX 
ON FIDE_VOTANTES_TB (Genero_ID);

CREATE INDEX FIDE_VOTANTES_TB_DIRECCION_ID_FK_IDX 
ON FIDE_VOTANTES_TB (Direccion_ID);

CREATE INDEX FIDE_VOTANTES_TB_ESTADO_ID_FK_IDX 
ON FIDE_VOTANTES_TB (Estado_ID);

-----------------------------------------------------------
ALTER INDEX SYS_C008594 
RENAME TO FIDE_VOTANTES_TB_EMAIL_UQ_IDX;
/
ALTER INDEX SYS_C008593 
RENAME TO FIDE_VOTANTES_TB_VOTANTE_ID_PK_IDX;
---OCTAVA TABLA
CREATE TABLE FIDE_ELECCIONES_TB(
    Eleccion_ID NUMBER PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Fecha_Inicio DATE NOT NULL,
    Fecha_Fin DATE NOT NULL,
    Descripcion VARCHAR2(255),
    Estado_ID NUMBER,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Estado_ID) REFERENCES FIDE_ESTADOS_TB(Estado_ID)
);
/
CREATE INDEX FIDE_ELECCIONES_TB_NOMBRE_IDX 
ON FIDE_ELECCIONES_TB (Nombre);

CREATE INDEX FIDE_ELECCIONES_TB_FECHA_INICIO_IDX 
ON FIDE_ELECCIONES_TB (Fecha_Inicio);

CREATE INDEX FIDE_ELECCIONES_TB_FECHA_FIN_IDX 
ON FIDE_ELECCIONES_TB (Fecha_Fin);

CREATE INDEX FIDE_ELECCIONES_TB_DESCRIPCION_IDX 
ON FIDE_ELECCIONES_TB (Descripcion);

CREATE INDEX FIDE_ELECCIONES_TB_ESTADO_ID_FK_IDX 
ON FIDE_ELECCIONES_TB (Estado_ID);

CREATE INDEX FIDE_ELECCIONES_TB_CREADO_POR_IDX 
ON FIDE_ELECCIONES_TB (creado_por);

CREATE INDEX FIDE_ELECCIONES_TB_MODIFICADO_POR_IDX 
ON FIDE_ELECCIONES_TB (modificado_por);

CREATE INDEX FIDE_ELECCIONES_TB_FECHA_CREACION_IDX 
ON FIDE_ELECCIONES_TB (fecha_creacion);

CREATE INDEX FIDE_ELECCIONES_TB_FECHA_MODIFICACION_IDX 
ON FIDE_ELECCIONES_TB (fecha_modificacion);

CREATE INDEX FIDE_ELECCIONES_TB_ACCION_IDX 
ON FIDE_ELECCIONES_TB (accion);
/
------------------------------------
ALTER INDEX SYS_C008601 
RENAME TO FIDE_ELECCIONES_TB_ELECCION_ID_PK_IDX;
/
---NOVENA TABLA
CREATE TABLE FIDE_PARTIDOS_TB(
    Partido_ID NUMBER PRIMARY KEY,
    Nombre VARCHAR2(50) UNIQUE NOT NULL,
    Siglas_Partido VARCHAR2(10) UNIQUE NOT NULL,
    Fecha_Fundacion DATE,
    Estado_ID NUMBER,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Estado_ID) REFERENCES FIDE_ESTADOS_TB(Estado_ID)
);
/
CREATE INDEX FIDE_PARTIDOS_TB_FECHA_FUNDACION_IDX 
ON FIDE_PARTIDOS_TB (Fecha_Fundacion);

CREATE INDEX FIDE_PARTIDOS_TB_ESTADO_ID_FK_IDX 
ON FIDE_PARTIDOS_TB (Estado_ID);

CREATE INDEX FIDE_PARTIDOS_TB_CREADO_POR_IDX 
ON FIDE_PARTIDOS_TB (creado_por);

CREATE INDEX FIDE_PARTIDOS_TB_MODIFICADO_POR_IDX 
ON FIDE_PARTIDOS_TB (modificado_por);

CREATE INDEX FIDE_PARTIDOS_TB_FECHA_CREACION_IDX 
ON FIDE_PARTIDOS_TB (fecha_creacion);

CREATE INDEX FIDE_PARTIDOS_TB_FECHA_MODIFICACION_IDX 
ON FIDE_PARTIDOS_TB (fecha_modificacion);

CREATE INDEX FIDE_PARTIDOS_TB_ACCION_IDX 
ON FIDE_PARTIDOS_TB (accion);
/
--------------------------------------------------
ALTER INDEX SYS_C008607
RENAME TO FIDE_PARTIDOS_TB_SIGLAS_PARTIDO_UQ_IDX;
/
ALTER INDEX SYS_C008605
RENAME TO FIDE_PARTIDOS_TB_PARTIDO_ID_PK_IDX;
/
ALTER INDEX SYS_C008606
RENAME TO FIDE_PARTIDOS_TB_NOMBRE_UQ_IDX;
/
---DECIMA TABLA
CREATE TABLE FIDE_CANDIDATOS_TB(
    Candidato_ID NUMBER PRIMARY KEY,
    Nombre VARCHAR2(50) NOT NULL,
    Apellido VARCHAR2(50) NOT NULL,
    Partido_ID NUMBER,
    Eleccion_ID NUMBER,
    Estado_ID NUMBER,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Partido_ID) REFERENCES FIDE_PARTIDOS_TB(Partido_ID),
    FOREIGN KEY (Eleccion_ID) REFERENCES FIDE_ELECCIONES_TB(Eleccion_ID),
    FOREIGN KEY (Estado_ID) REFERENCES FIDE_ESTADOS_TB(Estado_ID)
);
/
CREATE INDEX FIDE_CANDIDATOS_TB_NOMBRE_IDX 
ON FIDE_CANDIDATOS_TB (Nombre);

CREATE INDEX FIDE_CANDIDATOS_TB_APELLIDO_IDX 
ON FIDE_CANDIDATOS_TB (Apellido);

CREATE INDEX FIDE_CANDIDATOS_TB_PARTIDO_ID_FK_IDX 
ON FIDE_CANDIDATOS_TB (Partido_ID);

CREATE INDEX FIDE_CANDIDATOS_TB_ELECCION_ID_FK_IDX 
ON FIDE_CANDIDATOS_TB (Eleccion_ID);

CREATE INDEX FIDE_CANDIDATOS_TB_ESTADO_ID_FK_IDX 
ON FIDE_CANDIDATOS_TB (Estado_ID);

CREATE INDEX FIDE_CANDIDATOS_TB_CREADO_POR_IDX 
ON FIDE_CANDIDATOS_TB (creado_por);

CREATE INDEX FIDE_CANDIDATOS_TB_MODIFICADO_POR_IDX 
ON FIDE_CANDIDATOS_TB (modificado_por);

CREATE INDEX FIDE_CANDIDATOS_TB_FECHA_CREACION_IDX 
ON FIDE_CANDIDATOS_TB (fecha_creacion);

CREATE INDEX FIDE_CANDIDATOS_TB_FECHA_MODIFICACION_IDX 
ON FIDE_CANDIDATOS_TB (fecha_modificacion);

CREATE INDEX FIDE_CANDIDATOS_TB_ACCION_IDX 
ON FIDE_CANDIDATOS_TB (accion);
/
--------------------------------------------------------
ALTER INDEX SYS_C008611
RENAME TO FIDE_CANDIDATOS_TB_CANDIDATO_ID_PK_IDX;
/
---onceava tabla
CREATE TABLE FIDE_ROLES_TB(
    Rol_ID NUMBER PRIMARY KEY,
    Nombre_Rol VARCHAR2(50) UNIQUE NOT NULL,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100)
);
/
CREATE INDEX FIDE_ROLES_TB_CREADO_POR_IDX 
ON FIDE_ROLES_TB (creado_por);

CREATE INDEX FIDE_ROLES_TB_MODIFICADO_POR_IDX 
ON FIDE_ROLES_TB (modificado_por);

CREATE INDEX FIDE_ROLES_TB_FECHA_CREACION_IDX 
ON FIDE_ROLES_TB (fecha_creacion);

CREATE INDEX FIDE_ROLES_TB_FECHA_MODIFICACION_IDX 
ON FIDE_ROLES_TB (fecha_modificacion);

CREATE INDEX FIDE_ROLES_TB_ACCION_IDX 
ON FIDE_ROLES_TB (accion);
/
------------------------------------------------------
ALTER INDEX SYS_C008616
RENAME TO FIDE_ROLES_TB_ROL_ID_PK_IDX;
/
ALTER INDEX SYS_C008617
RENAME TO FIDE_ROLES_TB_NOMBRE_ROL_UQ_IDX;
/
---TABLA DOCE
CREATE TABLE FIDE_USUARIOS_TB(
    Usuario_ID NUMBER PRIMARY KEY,
    User_name VARCHAR2(50) UNIQUE NOT NULL,
    Password VARCHAR2(255) NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Rol_ID NUMBER,
    Estado_ID NUMBER,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Rol_ID) REFERENCES FIDE_ROLES_TB(Rol_ID),
    FOREIGN KEY (Estado_ID) REFERENCES FIDE_ESTADOS_TB(Estado_ID)
);
/
CREATE INDEX FIDE_USUARIOS_TB_ROL_ID_IDX 
ON FIDE_USUARIOS_TB (Rol_ID);

CREATE INDEX FIDE_USUARIOS_TB_ESTADO_ID_IDX 
ON FIDE_USUARIOS_TB (Estado_ID);

CREATE INDEX FIDE_USUARIOS_TB_CREADO_POR_IDX 
ON FIDE_USUARIOS_TB (creado_por);

CREATE INDEX FIDE_USUARIOS_TB_MODIFICADO_POR_IDX 
ON FIDE_USUARIOS_TB (modificado_por);

CREATE INDEX FIDE_USUARIOS_TB_FECHA_CREACION_IDX 
ON FIDE_USUARIOS_TB (fecha_creacion);

CREATE INDEX FIDE_USUARIOS_TB_FECHA_MODIFICACION_IDX 
ON FIDE_USUARIOS_TB (fecha_modificacion);

CREATE INDEX FIDE_USUARIOS_TB_ACCION_IDX 
ON FIDE_USUARIOS_TB (accion);
/
---------------------------------------------
ALTER INDEX SYS_C008621
RENAME TO FIDE_USUARIOS_TB_USUARIO_ID_PK_IDX;
/
ALTER INDEX SYS_C008622
RENAME TO FIDE_USUARIOS_TB_USER_NAME_UQ_IDX;
/
ALTER INDEX SYS_C008623
RENAME TO FIDE_USUARIOS_TB_EMAIL_UQ_IDX;
/
---TABLA TRECE
CREATE TABLE FIDE_AUDITORES_TB(
    Auditor_ID NUMBER PRIMARY KEY,
    Nombre VARCHAR2(50) NOT NULL,
    Apellido VARCHAR2(50) NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Telefono VARCHAR2(20),
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100)
);
/
CREATE INDEX FIDE_AUDITORES_TB_NOMBRE_IDX 
ON FIDE_AUDITORES_TB (Nombre);

CREATE INDEX FIDE_AUDITORES_TB_APELLIDO_IDX 
ON FIDE_AUDITORES_TB (Apellido);

CREATE INDEX FIDE_AUDITORES_TB_TELEFONO_IDX 
ON FIDE_AUDITORES_TB (Telefono);

CREATE INDEX FIDE_AUDITORES_TB_CREADO_POR_IDX 
ON FIDE_AUDITORES_TB (creado_por);

CREATE INDEX FIDE_AUDITORES_TB_MODIFICADO_POR_IDX 
ON FIDE_AUDITORES_TB (modificado_por);

CREATE INDEX FIDE_AUDITORES_TB_FECHA_CREACION_IDX 
ON FIDE_AUDITORES_TB (fecha_creacion);

CREATE INDEX FIDE_AUDITORES_TB_FECHA_MODIFICACION_IDX 
ON FIDE_AUDITORES_TB (fecha_modificacion);

CREATE INDEX FIDE_AUDITORES_TB_ACCION_IDX 
ON FIDE_AUDITORES_TB (accion);
/
-------------------------------------------------------
ALTER INDEX SYS_C008629
RENAME TO FIDE_AUDITORES_TB_AUDITOR_ID_PK_IDX;
/
ALTER INDEX SYS_C008630
RENAME TO FIDE_AUDITORES_TB_EMAIL_UQ_IDX;
/
---TABLA CATORCE
CREATE TABLE FIDE_AUDITORIAS_TB(
    Auditoria_ID NUMBER PRIMARY KEY,
    Eleccion_ID NUMBER,
    Auditor_ID NUMBER,
    Fecha_Auditoria DATE NOT NULL,
    Resultado VARCHAR2(255),
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Eleccion_ID) REFERENCES FIDE_ELECCIONES_TB(Eleccion_ID),
    FOREIGN KEY (Auditor_ID) REFERENCES FIDE_AUDITORES_TB(Auditor_ID)
);
/
CREATE INDEX FIDE_AUDITORIAS_TB_RESULTADO_IDX 
ON FIDE_AUDITORIAS_TB (Resultado);

CREATE INDEX FIDE_AUDITORIAS_TB_ELECCION_ID_IDX 
ON FIDE_AUDITORIAS_TB (Eleccion_ID);

CREATE INDEX FIDE_AUDITORIAS_TB_AUDITOR_ID_IDX 
ON FIDE_AUDITORIAS_TB (Auditor_ID);

CREATE INDEX FIDE_AUDITORIAS_TB_FECHA_AUDITORIA_IDX 
ON FIDE_AUDITORIAS_TB (Fecha_Auditoria);

CREATE INDEX FIDE_AUDITORIAS_TB_CREADO_POR_IDX 
ON FIDE_AUDITORIAS_TB (creado_por);

CREATE INDEX FIDE_AUDITORIAS_TB_MODIFICADO_POR_IDX 
ON FIDE_AUDITORIAS_TB (modificado_por);

CREATE INDEX FIDE_AUDITORIAS_TB_FECHA_CREACION_IDX 
ON FIDE_AUDITORIAS_TB (fecha_creacion);

CREATE INDEX FIDE_AUDITORIAS_TB_FECHA_MODIFICACION_IDX 
ON FIDE_AUDITORIAS_TB (fecha_modificacion);

CREATE INDEX FIDE_AUDITORIAS_TB_ACCION_IDX 
ON FIDE_AUDITORIAS_TB (accion);
/
-----------------------------------------------
ALTER INDEX SYS_C008632
RENAME TO FIDE_AUDITORIAS_TB_AUDITORIA_ID_PK_IDX;
/
---TABLA QUINCE
CREATE TABLE FIDE_SEDES_TB(
    Sede_ID NUMBER PRIMARY KEY,
    Nombre VARCHAR2(20) UNIQUE NOT NULL,
    Direccion_ID NUMBER,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Direccion_ID) REFERENCES FIDE_DIRECCIONES_TB(Direccion_ID)
);
/
CREATE INDEX FIDE_SEDES_TB_DIRECCION_ID_IDX 
ON FIDE_SEDES_TB (Direccion_ID);

CREATE INDEX FIDE_SEDES_TB_CREADO_POR_IDX 
ON FIDE_SEDES_TB (creado_por);

CREATE INDEX FIDE_SEDES_TB_MODIFICADO_POR_IDX 
ON FIDE_SEDES_TB (modificado_por);

CREATE INDEX FIDE_SEDES_TB_FECHA_CREACION_IDX 
ON FIDE_SEDES_TB (fecha_creacion);

CREATE INDEX FIDE_SEDES_TB_FECHA_MODIFICACION_IDX 
ON FIDE_SEDES_TB (fecha_modificacion);

CREATE INDEX FIDE_SEDES_TB_ACCION_IDX 
ON FIDE_SEDES_TB (accion);
/
------------------------------------------
ALTER INDEX SYS_C008636
RENAME TO FIDE_SEDES_TB_SEDE_ID_PK_IDX;
/
ALTER INDEX SYS_C008637
RENAME TO FIDE_SEDES_TB_NOMBRE_UQ_IDX;
/
---TABLA DIECISEIS
CREATE TABLE FIDE_VOTOS_TB(
    Voto_ID NUMBER PRIMARY KEY,
    Votante_ID NUMBER,
    Eleccion_ID NUMBER,
    Candidato_ID NUMBER,
    Fecha_Voto DATE NOT NULL,
    Detalle_Voto VARCHAR2(200),
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Votante_ID) REFERENCES FIDE_VOTANTES_TB(Votante_ID),
    FOREIGN KEY (Eleccion_ID) REFERENCES FIDE_ELECCIONES_TB(Eleccion_ID),
    FOREIGN KEY (Candidato_ID) REFERENCES FIDE_CANDIDATOS_TB(Candidato_ID)
);
/
CREATE INDEX FIDE_VOTOS_TB_VOTANTE_ID_IDX 
ON FIDE_VOTOS_TB (Votante_ID);

CREATE INDEX FIDE_VOTOS_TB_ELECCION_ID_IDX 
ON FIDE_VOTOS_TB (Eleccion_ID);

CREATE INDEX FIDE_VOTOS_TB_CANDIDATO_ID_IDX 
ON FIDE_VOTOS_TB (Candidato_ID);

CREATE INDEX FIDE_VOTOS_TB_FECHA_VOTO_IDX 
ON FIDE_VOTOS_TB (Fecha_Voto);

CREATE INDEX FIDE_VOTOS_TB_DETALLE_VOTO_IDX 
ON FIDE_VOTOS_TB (Detalle_Voto);

CREATE INDEX FIDE_VOTOS_TB_CREADO_POR_IDX 
ON FIDE_VOTOS_TB (creado_por);

CREATE INDEX FIDE_VOTOS_TB_MODIFICADO_POR_IDX 
ON FIDE_VOTOS_TB (modificado_por);

CREATE INDEX FIDE_VOTOS_TB_FECHA_CREACION_IDX 
ON FIDE_VOTOS_TB (fecha_creacion);

CREATE INDEX FIDE_VOTOS_TB_FECHA_MODIFICACION_IDX 
ON FIDE_VOTOS_TB (fecha_modificacion);

CREATE INDEX FIDE_VOTOS_TB_ACCION_IDX 
ON FIDE_VOTOS_TB (accion);
/
------------------------------------------------------------
ALTER INDEX SYS_C008640
RENAME TO FIDE_VOTOS_TB_VOTO_ID_PK_IDX;

ALTER INDEX SYS_C008930
RENAME TO FIDE_VOTANTES_TB_CEDULA_UNIQUE_IDX;
/
---TABLA DIECISIETE
CREATE TABLE FIDE_MESAS_VOTO_TB(
    Mesa_Voto_ID NUMBER PRIMARY KEY,
    Eleccion_ID NUMBER,
    Votante_ID NUMBER,
    Estado_ID NUMBER,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Eleccion_ID) REFERENCES FIDE_ELECCIONES_TB(Eleccion_ID),
    FOREIGN KEY (Votante_ID) REFERENCES FIDE_VOTANTES_TB(Votante_ID),
    FOREIGN KEY (Estado_ID) REFERENCES FIDE_ESTADOS_TB(Estado_ID)
);
/
CREATE INDEX FIDE_MESAS_VOTO_TB_ELECCION_ID_IDX 
ON FIDE_MESAS_VOTO_TB (Eleccion_ID);

CREATE INDEX FIDE_MESAS_VOTO_TB_VOTANTE_ID_IDX 
ON FIDE_MESAS_VOTO_TB (Votante_ID);

CREATE INDEX FIDE_MESAS_VOTO_TB_ESTADO_ID_IDX 
ON FIDE_MESAS_VOTO_TB (Estado_ID);

CREATE INDEX FIDE_MESAS_VOTO_TB_CREADO_POR_IDX 
ON FIDE_MESAS_VOTO_TB (creado_por);

CREATE INDEX FIDE_MESAS_VOTO_TB_MODIFICADO_POR_IDX 
ON FIDE_MESAS_VOTO_TB (modificado_por);

CREATE INDEX FIDE_MESAS_VOTO_TB_FECHA_CREACION_IDX 
ON FIDE_MESAS_VOTO_TB (fecha_creacion);

CREATE INDEX FIDE_MESAS_VOTO_TB_FECHA_MODIFICACION_IDX 
ON FIDE_MESAS_VOTO_TB (fecha_modificacion);

CREATE INDEX FIDE_MESAS_VOTO_TB_ACCION_IDX 
ON FIDE_MESAS_VOTO_TB (accion);
/
ALTER INDEX SYS_C008644
RENAME TO FIDE_MESAS_VOTO_TB_MESA_VOTO_ID_PK_IDX;
/
---TABLA DIECIOCHO
CREATE TABLE FIDE_CREDENCIALES_TB(
    Credencial_ID NUMBER PRIMARY KEY,
    Votante_ID NUMBER,
    Eleccion_ID NUMBER,
    Codigo VARCHAR2(50) UNIQUE NOT NULL,
    FechaEmision DATE NOT NULL,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Votante_ID) REFERENCES FIDE_VOTANTES_TB(Votante_ID),
    FOREIGN KEY (Eleccion_ID) REFERENCES FIDE_ELECCIONES_TB(Eleccion_ID)
);
/
CREATE INDEX FIDE_CREDENCIALES_TB_FECHA_EMISION_IDX 
ON FIDE_CREDENCIALES_TB (FechaEmision);

CREATE INDEX FIDE_CREDENCIALES_TB_VOTANTE_ID_IDX 
ON FIDE_CREDENCIALES_TB (Votante_ID);

CREATE INDEX FIDE_CREDENCIALES_TB_ELECCION_ID_IDX 
ON FIDE_CREDENCIALES_TB (Eleccion_ID);

CREATE INDEX FIDE_CREDENCIALES_TB_CREADO_POR_IDX 
ON FIDE_CREDENCIALES_TB (creado_por);

CREATE INDEX FIDE_CREDENCIALES_TB_MODIFICADO_POR_IDX 
ON FIDE_CREDENCIALES_TB (modificado_por);

CREATE INDEX FIDE_CREDENCIALES_TB_FECHA_CREACION_IDX 
ON FIDE_CREDENCIALES_TB (fecha_creacion);

CREATE INDEX FIDE_CREDENCIALES_TB_FECHA_MODIFICACION_IDX 
ON FIDE_CREDENCIALES_TB (fecha_modificacion);

CREATE INDEX FIDE_CREDENCIALES_TB_ACCION_IDX 
ON FIDE_CREDENCIALES_TB (accion);
/
-------------------------------------------------
ALTER INDEX SYS_C008650
RENAME TO FIDE_CREDENCIALES_TB_CREDENCIAL_ID_PK_IDX;
/
ALTER INDEX SYS_C008651
RENAME TO FIDE_CREDENCIALES_TB_CODIGO_UQ_IDX;
/
---TABLA DIECINUEVE
CREATE TABLE FIDE_REPORTES_TB(
    Reporte_ID NUMBER PRIMARY KEY,
    Eleccion_ID NUMBER,
    Votante_ID NUMBER,
    FechaReporte DATE NOT NULL,
    Descripcion VARCHAR2(255),
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Eleccion_ID) REFERENCES FIDE_ELECCIONES_TB(Eleccion_ID),
    FOREIGN KEY (Votante_ID) REFERENCES FIDE_VOTANTES_TB(Votante_ID)
);
/
CREATE INDEX FIDE_REPORTES_TB_ELECCION_ID_IDX 
ON FIDE_REPORTES_TB (Eleccion_ID);

CREATE INDEX FIDE_REPORTES_TB_VOTANTE_ID_IDX 
ON FIDE_REPORTES_TB (Votante_ID);

CREATE INDEX FIDE_REPORTES_TB_FECHA_REPORTE_IDX 
ON FIDE_REPORTES_TB (FechaReporte);
/
-------------------------------------------------
ALTER INDEX SYS_C008655
RENAME TO FIDE_REPORTES_TB_REPORTE_ID_PK_IDX;
/
---TABLA VEINTE
CREATE TABLE FIDE_BOLETAS_TB(
    Boleta_ID NUMBER PRIMARY KEY,
    Eleccion_ID NUMBER,
    Votante_ID NUMBER,
    Candidato_ID NUMBER,
    FechaBoleta DATE NOT NULL,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Eleccion_ID) REFERENCES FIDE_ELECCIONES_TB(Eleccion_ID),
    FOREIGN KEY (Votante_ID) REFERENCES FIDE_VOTANTES_TB(Votante_ID),
    FOREIGN KEY (Candidato_ID) REFERENCES FIDE_CANDIDATOS_TB(Candidato_ID)
);
/
CREATE INDEX FIDE_BOLETAS_TB_ELECCION_ID_IDX 
ON FIDE_BOLETAS_TB (Eleccion_ID);

CREATE INDEX FIDE_BOLETAS_TB_VOTANTE_ID_IDX 
ON FIDE_BOLETAS_TB (Votante_ID);

CREATE INDEX FIDE_BOLETAS_TB_CANDIDATO_ID_IDX 
ON FIDE_BOLETAS_TB (Candidato_ID);

CREATE INDEX FIDE_BOLETAS_TB_FECHA_BOLETA_IDX 
ON FIDE_BOLETAS_TB (FechaBoleta);

CREATE INDEX FIDE_BOLETAS_TB_CREADO_POR_IDX 
ON FIDE_BOLETAS_TB (creado_por);

CREATE INDEX FIDE_BOLETAS_TB_MODIFICADO_POR_IDX 
ON FIDE_BOLETAS_TB (modificado_por);

CREATE INDEX FIDE_BOLETAS_TB_FECHA_CREACION_IDX 
ON FIDE_BOLETAS_TB (fecha_creacion);

CREATE INDEX FIDE_BOLETAS_TB_FECHA_MODIFICACION_IDX 
ON FIDE_BOLETAS_TB (fecha_modificacion);

CREATE INDEX FIDE_BOLETAS_TB_ACCION_IDX 
ON FIDE_BOLETAS_TB (accion);
/
------------------------------------------------------
ALTER INDEX SYS_C008659
RENAME TO FIDE_BOLETAS_TB_BOLETA_ID_PK_IDX;
/
---TABLA VEINTIUNO
CREATE TABLE FIDE_CLAVES_SEGURIDAD_TB(
    Clave_ID NUMBER PRIMARY KEY,
    Votante_ID NUMBER,
    Clave VARCHAR2(255) NOT NULL,
    FechaCreacion DATE NOT NULL,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Votante_ID) REFERENCES FIDE_VOTANTES_TB(Votante_ID)
);
/
CREATE INDEX FIDE_CLAVES_SEGURIDAD_TB_VOTANTE_ID_IDX 
ON FIDE_CLAVES_SEGURIDAD_TB (Votante_ID);

CREATE INDEX FIDE_CLAVES_SEGURIDAD_TB_CLAVE_IDX 
ON FIDE_CLAVES_SEGURIDAD_TB (Clave);

CREATE INDEX FIDE_CLAVES_SEGURIDAD_TB_FECHA_CREACION_IDX 
ON FIDE_CLAVES_SEGURIDAD_TB (FechaCreacion);

CREATE INDEX FIDE_CLAVES_SEGURIDAD_TB_CREADO_POR_IDX 
ON FIDE_CLAVES_SEGURIDAD_TB (creado_por);

CREATE INDEX FIDE_CLAVES_SEGURIDAD_TB_MODIFICADO_POR_IDX 
ON FIDE_CLAVES_SEGURIDAD_TB (modificado_por);

CREATE INDEX FIDE_CLAVES_SEGURIDAD_TB_FECHA_CREACION_IDX 
ON FIDE_CLAVES_SEGURIDAD_TB (fecha_creacion);

CREATE INDEX FIDE_CLAVES_SEGURIDAD_TB_FECHA_MODIFICACION_IDX 
ON FIDE_CLAVES_SEGURIDAD_TB (fecha_modificacion);

CREATE INDEX FIDE_CLAVES_SEGURIDAD_TB_ACCION_IDX 
ON FIDE_CLAVES_SEGURIDAD_TB (accion);
/
------------------------------------------------------------
ALTER INDEX SYS_C008665
RENAME TO FIDE_CLAVES_SEGURIDAD_TB_CLAVE_ID_PK_IDX;
/
---TABLA VEINTEDOS
CREATE TABLE FIDE_LOGSEGURIDAD_TB(
    Log_ID NUMBER PRIMARY KEY,
    Votante_ID NUMBER,
    Fecha DATE NOT NULL,
    Accion_log VARCHAR2(255) NOT NULL,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Votante_ID) REFERENCES FIDE_VOTANTES_TB(Votante_ID)
);
/
CREATE INDEX FIDE_LOGSEGURIDAD_TB_VOTANTE_ID_IDX 
ON FIDE_LOGSEGURIDAD_TB (Votante_ID);

CREATE INDEX FIDE_LOGSEGURIDAD_TB_FECHA_IDX 
ON FIDE_LOGSEGURIDAD_TB (Fecha);

CREATE INDEX FIDE_LOGSEGURIDAD_TB_ACCION_LOG_IDX 
ON FIDE_LOGSEGURIDAD_TB (Accion_log);

CREATE INDEX FIDE_LOGSEGURIDAD_TB_CREADO_POR_IDX 
ON FIDE_LOGSEGURIDAD_TB (creado_por);

CREATE INDEX FIDE_LOGSEGURIDAD_TB_MODIFICADO_POR_IDX 
ON FIDE_LOGSEGURIDAD_TB (modificado_por);

CREATE INDEX FIDE_LOGSEGURIDAD_TB_FECHA_CREACION_IDX 
ON FIDE_LOGSEGURIDAD_TB (fecha_creacion);

CREATE INDEX FIDE_LOGSEGURIDAD_TB_FECHA_MODIFICACION_IDX 
ON FIDE_LOGSEGURIDAD_TB (fecha_modificacion);

CREATE INDEX FIDE_LOGSEGURIDAD_TB_ACCION_IDX 
ON FIDE_LOGSEGURIDAD_TB (accion);
/
----------------------------------------------------------------------
ALTER INDEX SYS_C008669
RENAME TO FIDE_LOGSEGURIDAD_TB_LOG_ID_PK_IDX;
/
---TABLA VEINTETRES
CREATE TABLE FIDE_NOTIFICACIONES_TB(
    Notificacion_ID NUMBER PRIMARY KEY,
    Votante_ID NUMBER,
    Mensaje VARCHAR2(255) NOT NULL,
    FechaNotificacion DATE NOT NULL,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Votante_ID) REFERENCES FIDE_VOTANTES_TB(Votante_ID)
);
/
CREATE INDEX FIDE_NOTIFICACIONES_TB_VOTANTE_ID_IDX 
ON FIDE_NOTIFICACIONES_TB (Votante_ID);

CREATE INDEX FIDE_NOTIFICACIONES_TB_FECHANOTIFICACION_IDX 
ON FIDE_NOTIFICACIONES_TB (FechaNotificacion);

CREATE INDEX FIDE_NOTIFICACIONES_TB_MENSAJE_IDX 
ON FIDE_NOTIFICACIONES_TB (Mensaje);

CREATE INDEX FIDE_NOTIFICACIONES_TB_CREADO_POR_IDX 
ON FIDE_NOTIFICACIONES_TB (creado_por);

CREATE INDEX FIDE_NOTIFICACIONES_TB_MODIFICADO_POR_IDX 
ON FIDE_NOTIFICACIONES_TB (modificado_por);

CREATE INDEX FIDE_NOTIFICACIONES_TB_FECHA_CREACION_IDX 
ON FIDE_NOTIFICACIONES_TB (fecha_creacion);

CREATE INDEX FIDE_NOTIFICACIONES_TB_FECHA_MODIFICACION_IDX 
ON FIDE_NOTIFICACIONES_TB (fecha_modificacion);

CREATE INDEX FIDE_NOTIFICACIONES_TB_ACCION_IDX 
ON FIDE_NOTIFICACIONES_TB (accion);
/
---------------------------------------------------------------
ALTER INDEX SYS_C008673
RENAME TO FIDE_NOTIFICACIONES_TB_NOTIFICACION_ID_PK_IDX;
/
---TABLA VEINTECUATRO
CREATE TABLE FIDE_SESIONES_TB(
    Sesion_ID NUMBER PRIMARY KEY,
    Usuario_ID NUMBER,
    FechaInicio DATE NOT NULL,
    FechaFin DATE,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Usuario_ID) REFERENCES FIDE_USUARIOS_TB(Usuario_ID)
);
/
CREATE INDEX FIDE_SESIONES_TB_USUARIO_ID_IDX
ON FIDE_SESIONES_TB (Usuario_ID);

CREATE INDEX FIDE_SESIONES_TB_FECHA_INICIO_IDX
ON FIDE_SESIONES_TB (FechaInicio);

CREATE INDEX FIDE_SESIONES_TB_FECHA_FIN_IDX
ON FIDE_SESIONES_TB (FechaFin);
/
------------------------------------------------------------
ALTER INDEX SYS_C008676
RENAME TO FIDE_SESIONES_TB_SESION_ID_PK_IDX;
/
---TABLA VEINTECINCO
CREATE TABLE FIDE_HISTORIALVOTOS_TB(
    Historial_ID NUMBER PRIMARY KEY,
    FechaModificacion DATE NOT NULL,
    Accion_historial VARCHAR2(50) NOT NULL,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100)
);
/
CREATE INDEX FIDE_HISTORIALVOTOS_TB_FECHA_MODIFICACION_IDX
ON FIDE_HISTORIALVOTOS_TB (FechaModificacion);

CREATE INDEX FIDE_HISTORIALVOTOS_TB_ACCION_HISTORIAL_IDX
ON FIDE_HISTORIALVOTOS_TB (Accion_historial);

CREATE INDEX FIDE_HISTORIALVOTOS_TB_FECHA_CREACION_IDX
ON FIDE_HISTORIALVOTOS_TB (fecha_creacion);
/
------------------------------------------------------------------
ALTER INDEX SYS_C008680
RENAME TO FIDE_HISTORIALVOTOS_TB_HISTORIAL_ID_PK_IDX;
/
---TABLA VEINTESEIS
CREATE TABLE FIDE_VOTOS_HISTORIAL_TB(
    Votos_Historial_ID NUMBER PRIMARY KEY,
    Voto_ID NUMBER,
    Historial_ID NUMBER,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Voto_ID) REFERENCES FIDE_VOTOS_TB(Voto_ID),
    FOREIGN KEY (Historial_ID) REFERENCES FIDE_HISTORIALVOTOS_TB(Historial_ID)
);
/
CREATE INDEX FIDE_VOTOS_HISTORIAL_TB_VOTO_ID_IDX
ON FIDE_VOTOS_HISTORIAL_TB (Voto_ID);

CREATE INDEX FIDE_VOTOS_HISTORIAL_TB_HISTORIAL_ID_IDX
ON FIDE_VOTOS_HISTORIAL_TB (Historial_ID);

CREATE INDEX FIDE_VOTOS_HISTORIAL_TB_FECHA_CREACION_IDX
ON FIDE_VOTOS_HISTORIAL_TB (fecha_creacion);
/
---------------------------------------------------------------------
ALTER INDEX SYS_C008681
RENAME TO FIDE_VOTOS_HISTORIAL_TB_VOTOS_HISTORIAL_ID_PK_IDX;
/
---TABLA VENTISIETE
CREATE TABLE FIDE_RESULTADOS_TB(
    Resultado_ID NUMBER PRIMARY KEY,
    Eleccion_ID NUMBER,
    Candidato_ID NUMBER,
    Estado_ID NUMBER,
    Votos_Obtenidos NUMBER,
    creado_por VARCHAR2(50),
    modificado_por VARCHAR2(50),
    fecha_creacion DATE,
    fecha_modificacion DATE,
    accion VARCHAR2(100),
    FOREIGN KEY (Eleccion_ID) REFERENCES FIDE_ELECCIONES_TB(Eleccion_ID),
    FOREIGN KEY (Candidato_ID) REFERENCES FIDE_CANDIDATOS_TB(Candidato_ID),
    FOREIGN KEY (Estado_ID) REFERENCES FIDE_ESTADOS_TB(Estado_ID)
);
/
CREATE INDEX FIDE_RESULTADOS_TB_ELECCION_ID_IDX
ON FIDE_RESULTADOS_TB (Eleccion_ID);

CREATE INDEX FIDE_RESULTADOS_TB_CANDIDATO_ID_IDX
ON FIDE_RESULTADOS_TB (Candidato_ID);

CREATE INDEX FIDE_RESULTADOS_TB_ESTADO_ID_IDX
ON FIDE_RESULTADOS_TB (Estado_ID);

CREATE INDEX FIDE_RESULTADOS_TB_FECHA_CREACION_IDX
ON FIDE_RESULTADOS_TB (fecha_creacion);
/
--------------------------------------------------------------------------------
ALTER INDEX SYS_C008684
RENAME TO FIDE_RESULTADOS_TB_RESULTADO_ID_PK_IDX;
/