-----AUDITORES
CREATE SEQUENCE AUDITOR_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_AUDITORES_AUDITOR_ID_TRG
BEFORE INSERT ON FIDE_AUDITORES_TB
FOR EACH ROW
BEGIN
    :NEW.AUDITOR_ID := AUDITOR_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_AUDITORES_CREADO_POR_TRG
BEFORE INSERT ON FIDE_AUDITORES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_AUDITORES_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_AUDITORES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_AUDITORES_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_AUDITORES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
------------------------------------AUDITORIAS---------------------------------------------------------
CREATE SEQUENCE AUDITORIA_ID_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_AUDITORIAS_AUDITORIA_ID_TRG
BEFORE INSERT ON FIDE_AUDITORIAS_TB
FOR EACH ROW
BEGIN
    :NEW.AUDITORIA_ID := AUDITORIA_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_AUDITORIAS_CREADO_POR_TRG
BEFORE INSERT ON FIDE_AUDITORIAS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_AUDITORIAS_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_AUDITORIAS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_AUDITORIAS_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_AUDITORIAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
------------------------------------BOLETAS---------------------------------------------------------
CREATE SEQUENCE BOLETA_ID_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_BOLETAS_BOLETA_ID_TRG
BEFORE INSERT ON FIDE_BOLETAS_TB
FOR EACH ROW
BEGIN
    :NEW.BOLETA_ID := BOLETA_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_BOLETAS_CREADO_POR_TRG
BEFORE INSERT ON FIDE_BOLETAS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_BOLETAS_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_BOLETAS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_BOLETAS_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_BOLETAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
------------------------------------CANDIDATOS---------------------------------------------------------
CREATE SEQUENCE CANDIDATO_ID_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_CANDIDATOS_CANDIDATO_ID_TRG
BEFORE INSERT ON FIDE_CANDIDATOS_TB
FOR EACH ROW
BEGIN
    :NEW.CANDIDATO_ID := CANDIDATO_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CANDIDATOS_CREADO_POR_TRG
BEFORE INSERT ON FIDE_CANDIDATOS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_CANDIDATOS_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANDIDATOS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_CANDIDATOS_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANDIDATOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
------------------------------------CANTONES---------------------------------------------------------
CREATE SEQUENCE CANTON_ID_SEQ
START WITH 1
INCREMENT BY 1;
--DROP SEQUENCE DIRECCION_ID_SEQ;
/
CREATE OR REPLACE TRIGGER FIDE_CANTONES_CANTON_ID_TRG
BEFORE INSERT ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
    :NEW.CANTON_ID := CANTON_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_CANTONES_CREADO_POR_TRG
BEFORE INSERT ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_CANTONES_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_CANTONES_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
------------------------------------CLAVES_SEGURIDAD---------------------------------------------------------
CREATE SEQUENCE CLAVE_ID_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_CLAVES_SEGURIDAD_CLAVE_ID_TRG
BEFORE INSERT ON FIDE_CLAVES_SEGURIDAD_TB
FOR EACH ROW
BEGIN
    :NEW.CLAVE_ID := CLAVE_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_CLAVES_SEGURIDAD_CREADO_POR_TRG
BEFORE INSERT ON FIDE_CLAVES_SEGURIDAD_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_CLAVES_SEGURIDAD_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CLAVES_SEGURIDAD_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_CLAVES_SEGURIDAD_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CLAVES_SEGURIDAD_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
------------------------------------CREDENCIALES---------------------------------------------------------
CREATE SEQUENCE CREDENCIAL_ID_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_CREDENCIALES_CREDENCIAL_ID_TRG
BEFORE INSERT ON FIDE_CREDENCIALES_TB
FOR EACH ROW
BEGIN
    :NEW.CREDENCIAL_ID := CREDENCIAL_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_CREDENCIALES_CREADO_POR_TRG
BEFORE INSERT ON FIDE_CREDENCIALES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_CREDENCIALES_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CREDENCIALES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_CREDENCIALES_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CREDENCIALES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
------------------------------------DIRECCIONES---------------------------------------------------------
CREATE SEQUENCE DIRECCION_ID_SEQ
START WITH 1
INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_DIRECCION_ID_TRG
BEFORE INSERT ON FIDE_DIRECCIONES_TB
FOR EACH ROW
BEGIN
    :NEW.DIRECCION_ID := DIRECCION_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_CREADO_POR_TRG
BEFORE INSERT ON FIDE_DIRECCIONES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCIONES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCIONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
-- FIDE_ESTADOS_TB
CREATE SEQUENCE ESTADO_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_ESTADOS_ESTADO_ID_TRG
BEFORE INSERT ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
    :NEW.Estado_ID := ESTADO_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_ESTADOS_CREADO_POR_TRG
BEFORE INSERT ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_ESTADOS_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_ESTADOS_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;

-- FIDE_GENEROS_TB
CREATE SEQUENCE GENERO_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_GENEROS_GENERO_ID_TRG
BEFORE INSERT ON FIDE_GENEROS_TB
FOR EACH ROW
BEGIN
    :NEW.Genero_ID := GENERO_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_GENEROS_CREADO_POR_TRG
BEFORE INSERT ON FIDE_GENEROS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_GENEROS_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_GENEROS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_GENEROS_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_GENEROS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
-- FIDE_PROVINCIAS_TB
CREATE SEQUENCE PROVINCIA_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_PROVINCIAS_PROVINCIA_ID_TRG
BEFORE INSERT ON FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
    :NEW.Provincia_ID := PROVINCIA_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_PROVINCIAS_CREADO_POR_TRG
BEFORE INSERT ON FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_PROVINCIAS_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_PROVINCIAS_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
-- FIDE_DISTRITOS_TB
CREATE SEQUENCE DISTRITO_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_DISTRITO_ID_TRG
BEFORE INSERT ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
    :NEW.Distrito_ID := DISTRITO_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_CREADO_POR_TRG
BEFORE INSERT ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
-- FIDE_VOTANTES_TB
CREATE SEQUENCE VOTANTE_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_VOTANTES_VOTANTE_ID_TRG
BEFORE INSERT ON FIDE_VOTANTES_TB
FOR EACH ROW
BEGIN
    :NEW.Votante_ID := VOTANTE_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_VOTANTES_CREADO_POR_TRG
BEFORE INSERT ON FIDE_VOTANTES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_VOTANTES_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_VOTANTES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_VOTANTES_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_VOTANTES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
-- FIDE_ELECCIONES_TB
CREATE SEQUENCE ELECCION_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_ELECCIONES_ELECCION_ID_TRG
BEFORE INSERT ON FIDE_ELECCIONES_TB
FOR EACH ROW
BEGIN
    :NEW.Eleccion_ID := ELECCION_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_ELECCIONES_CREADO_POR_TRG
BEFORE INSERT ON FIDE_ELECCIONES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_ELECCIONES_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_ELECCIONES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_ELECCIONES_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ELECCIONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
-- FIDE_PARTIDOS_TB
CREATE SEQUENCE PARTIDO_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_PARTIDOS_PARTIDO_ID_TRG
BEFORE INSERT ON FIDE_PARTIDOS_TB
FOR EACH ROW
BEGIN
    :NEW.Partido_ID := PARTIDO_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_PARTIDOS_CREADO_POR_TRG
BEFORE INSERT ON FIDE_PARTIDOS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_PARTIDOS_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PARTIDOS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_PARTIDOS_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PARTIDOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
-- FIDE_ROLES_TB
CREATE SEQUENCE ROL_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_ROLES_ROL_ID_TRG
BEFORE INSERT ON FIDE_ROLES_TB
FOR EACH ROW
BEGIN
    :NEW.Rol_ID := ROL_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_ROLES_CREADO_POR_TRG
BEFORE INSERT ON FIDE_ROLES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_ROLES_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROLES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_ROLES_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROLES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
-- FIDE_USUARIOS_TB
CREATE SEQUENCE USUARIO_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_USUARIOS_USUARIO_ID_TRG
BEFORE INSERT ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
    :NEW.Usuario_ID := USUARIO_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_USUARIOS_CREADO_POR_TRG
BEFORE INSERT ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_USUARIOS_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_USUARIOS_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
-- FIDE_SEDES_TB
CREATE SEQUENCE SEDE_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_SEDES_SEDE_ID_TRG
BEFORE INSERT ON FIDE_SEDES_TB
FOR EACH ROW
BEGIN
    :NEW.Sede_ID := SEDE_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_SEDES_CREADO_POR_TRG
BEFORE INSERT ON FIDE_SEDES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_SEDES_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_SEDES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_SEDES_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_SEDES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
-- FIDE_VOTOS_TB
CREATE SEQUENCE VOTO_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_VOTOS_VOTO_ID_TRG
BEFORE INSERT ON FIDE_VOTOS_TB
FOR EACH ROW
BEGIN
    :NEW.Voto_ID := VOTO_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_VOTOS_CREADO_POR_TRG
BEFORE INSERT ON FIDE_VOTOS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_VOTOS_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_VOTOS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_VOTOS_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_VOTOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
-- FIDE_MESAS_VOTO_TB
CREATE SEQUENCE MESA_VOTO_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_MESAS_VOTO_MESA_VOTO_ID_TRG
BEFORE INSERT ON FIDE_MESAS_VOTO_TB
FOR EACH ROW
BEGIN
    :NEW.Mesa_Voto_ID := MESA_VOTO_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_MESAS_VOTO_CREADO_POR_TRG
BEFORE INSERT ON FIDE_MESAS_VOTO_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_MESAS_VOTO_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_MESAS_VOTO_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_MESAS_VOTO_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_MESAS_VOTO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
-- FIDE_REPORTES_TB
CREATE SEQUENCE REPORTE_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_REPORTES_REPORTE_ID_TRG
BEFORE INSERT ON FIDE_REPORTES_TB
FOR EACH ROW
BEGIN
    :NEW.Reporte_ID := REPORTE_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_REPORTES_CREADO_POR_TRG
BEFORE INSERT ON FIDE_REPORTES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_REPORTES_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_REPORTES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_REPORTES_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_REPORTES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
-- FIDE_LOGSEGURIDAD_TB
CREATE SEQUENCE LOG_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_LOGSEGURIDAD_LOG_ID_TRG
BEFORE INSERT ON FIDE_LOGSEGURIDAD_TB
FOR EACH ROW
BEGIN
    :NEW.Log_ID := LOG_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_LOGSEGURIDAD_CREADO_POR_TRG
BEFORE INSERT ON FIDE_LOGSEGURIDAD_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_LOGSEGURIDAD_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_LOGSEGURIDAD_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_LOGSEGURIDAD_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_LOGSEGURIDAD_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
-- FIDE_NOTIFICACIONES_TB
CREATE SEQUENCE NOTIFICACION_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_NOTIFICACIONES_NOTIFICACION_ID_TRG
BEFORE INSERT ON FIDE_NOTIFICACIONES_TB
FOR EACH ROW
BEGIN
    :NEW.Notificacion_ID := NOTIFICACION_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_NOTIFICACIONES_CREADO_POR_TRG
BEFORE INSERT ON FIDE_NOTIFICACIONES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_NOTIFICACIONES_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_NOTIFICACIONES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_NOTIFICACIONES_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_NOTIFICACIONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
-- FIDE_SESIONES_TB
CREATE SEQUENCE SESION_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_SESIONES_SESION_ID_TRG
BEFORE INSERT ON FIDE_SESIONES_TB
FOR EACH ROW
BEGIN
    :NEW.Sesion_ID := SESION_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_SESIONES_CREADO_POR_TRG
BEFORE INSERT ON FIDE_SESIONES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_SESIONES_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_SESIONES_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_SESIONES_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_SESIONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
-- FIDE_HISTORIALVOTOS_TB
CREATE SEQUENCE HISTORIAL_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_HISTORIALVOTOS_HISTORIAL_ID_TRG
BEFORE INSERT ON FIDE_HISTORIALVOTOS_TB
FOR EACH ROW
BEGIN
    :NEW.Historial_ID := HISTORIAL_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_HISTORIALVOTOS_CREADO_POR_TRG
BEFORE INSERT ON FIDE_HISTORIALVOTOS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_HISTORIALVOTOS_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_HISTORIALVOTOS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_HISTORIALVOTOS_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_HISTORIALVOTOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
-- FIDE_VOTOS_HISTORIAL_TB
CREATE SEQUENCE VOTOS_HISTORIAL_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_VOTOS_HISTORIAL_VOTOS_HISTORIAL_ID_TRG
BEFORE INSERT ON FIDE_VOTOS_HISTORIAL_TB
FOR EACH ROW
BEGIN
    :NEW.Votos_Historial_ID := VOTOS_HISTORIAL_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_VOTOS_HISTORIAL_CREADO_POR_TRG
BEFORE INSERT ON FIDE_VOTOS_HISTORIAL_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_VOTOS_HISTORIAL_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_VOTOS_HISTORIAL_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_VOTOS_HISTORIAL_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_VOTOS_HISTORIAL_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
/
-- FIDE_RESULTADOS_TB
CREATE SEQUENCE RESULTADO_ID_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER FIDE_RESULTADOS_RESULTADO_ID_TRG
BEFORE INSERT ON FIDE_RESULTADOS_TB
FOR EACH ROW
BEGIN
    :NEW.Resultado_ID := RESULTADO_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_RESULTADOS_CREADO_POR_TRG
BEFORE INSERT ON FIDE_RESULTADOS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_creacion := SYSTIMESTAMP;
    :NEW.Creado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_RESULTADOS_ACTUALIZADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_RESULTADOS_TB
FOR EACH ROW
BEGIN
    :NEW.Fecha_modificacion := SYSTIMESTAMP;
    :NEW.modificado_por := USER;
END;
/
CREATE OR REPLACE TRIGGER FIDE_RESULTADOS_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_RESULTADOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
    :NEW.Accion := 'INSERT';
ELSIF UPDATING THEN
    :NEW.Accion := 'UPDATE';
END IF;
END;
