TRUNCATE TABLE FIDE_ESTADOS_TB;
TRUNCATE TABLE FIDE_GENEROS_TB;
TRUNCATE TABLE FIDE_PROVINCIAS_TB;
TRUNCATE TABLE FIDE_CANTONES_TB;
TRUNCATE TABLE FIDE_DISTRITOS_TB;
TRUNCATE TABLE FIDE_DIRECCIONES_TB;
TRUNCATE TABLE FIDE_VOTANTES_TB;
TRUNCATE TABLE FIDE_ELECCIONES_TB;
TRUNCATE TABLE FIDE_PARTIDOS_TB;
TRUNCATE TABLE FIDE_CANDIDATOS_TB;
TRUNCATE TABLE FIDE_ROLES_TB;
TRUNCATE TABLE FIDE_USUARIOS_TB;
TRUNCATE TABLE FIDE_AUDITORES_TB;
TRUNCATE TABLE FIDE_AUDITORIAS_TB;
TRUNCATE TABLE FIDE_SEDES_TB;
TRUNCATE TABLE FIDE_VOTOS_TB;
TRUNCATE TABLE FIDE_MESAS_VOTO_TB;
TRUNCATE TABLE FIDE_CREDENCIALES_TB;
TRUNCATE TABLE FIDE_REPORTES_TB;
TRUNCATE TABLE FIDE_BOLETAS_TB;
TRUNCATE TABLE FIDE_CLAVES_SEGURIDAD_TB;
TRUNCATE TABLE FIDE_LOGSEGURIDAD_TB;
TRUNCATE TABLE FIDE_NOTIFICACIONES_TB;
TRUNCATE TABLE FIDE_SESIONES_TB;
TRUNCATE TABLE FIDE_HISTORIALVOTOS_TB;
TRUNCATE TABLE FIDE_VOTOS_HISTORIAL_TB;
TRUNCATE TABLE FIDE_RESULTADOS_TB;

-- FIDE_ESTADOS_TB
ALTER TABLE FIDE_ESTADOS_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_GENEROS_TB
ALTER TABLE FIDE_GENEROS_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_PROVINCIAS_TB
ALTER TABLE FIDE_PROVINCIAS_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_CANTONES_TB
ALTER TABLE FIDE_CANTONES_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_DISTRITOS_TB
ALTER TABLE FIDE_DISTRITOS_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_DIRECCIONES_TB
ALTER TABLE FIDE_DIRECCIONES_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_VOTANTES_TB
ALTER TABLE FIDE_VOTANTES_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_ELECCIONES_TB
ALTER TABLE FIDE_ELECCIONES_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_PARTIDOS_TB
ALTER TABLE FIDE_PARTIDOS_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_CANDIDATOS_TB
ALTER TABLE FIDE_CANDIDATOS_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_ROLES_TB
ALTER TABLE FIDE_ROLES_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_USUARIOS_TB
ALTER TABLE FIDE_USUARIOS_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_AUDITORES_TB
ALTER TABLE FIDE_AUDITORES_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_AUDITORIAS_TB
ALTER TABLE FIDE_AUDITORIAS_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_SEDES_TB
ALTER TABLE FIDE_SEDES_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_VOTOS_TB
ALTER TABLE FIDE_VOTOS_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_MESAS_VOTO_TB
ALTER TABLE FIDE_MESAS_VOTO_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_CREDENCIALES_TB
ALTER TABLE FIDE_CREDENCIALES_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_REPORTES_TB
ALTER TABLE FIDE_REPORTES_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_BOLETAS_TB
ALTER TABLE FIDE_BOLETAS_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_CLAVES_SEGURIDAD_TB
ALTER TABLE FIDE_CLAVES_SEGURIDAD_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_LOGSEGURIDAD_TB
ALTER TABLE FIDE_LOGSEGURIDAD_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_NOTIFICACIONES_TB
ALTER TABLE FIDE_NOTIFICACIONES_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_SESIONES_TB
ALTER TABLE FIDE_SESIONES_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP, fechaInicio TIMESTAMP, fechaFin TIMESTAMP);

-- FIDE_HISTORIALVOTOS_TB
ALTER TABLE FIDE_HISTORIALVOTOS_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_VOTOS_HISTORIAL_TB
ALTER TABLE FIDE_VOTOS_HISTORIAL_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

-- FIDE_RESULTADOS_TB
ALTER TABLE FIDE_RESULTADOS_TB MODIFY (fecha_creacion TIMESTAMP, fecha_modificacion TIMESTAMP);

